### ISSUE TITLE
Project - Group Number?

### ISSUE THREAD

**Issue by Chrystallic** [kbalog/ir-course#11]
The mail we received about team allocations contain only information about who we are teamed up with and what project we've gotten, but not the actual group-number
The table showing what timeslot each group has on github, only show the group-number and time-period, and not the name of the group-members. 

Could you please update the table to also contain the names of the students, or send each group a mail informing us of the groupnumber?

Currently we do not have any way to actually know our groupnumber (as far as I can see at least)

@kbalog @tlinjordet

**Comment by kbalog** [comment]
Group numbers have been emailed out

**Comment by Chrystallic** [comment]
Thank you

**Comment by Chrystallic** [comment]
Issue resolved
