### ISSUE TITLE
A5 Performance Improvement + Confusion

### ISSUE THREAD

**Issue by BerntA** [kbalog/ir-course#6]
Hey, in **get_doc_term_freqs**, could we please change **es.termvectors(index=index, id=doc_id, fields=field, term_statistics=True)** to **es.termvectors(index=index, id=doc_id, fields=field, term_statistics=False)** since we only need 'term_freq' here. Retrieving term statistics across the entire field in the corpus here is unnecessary and degrades the performance a lot when dealing with the large dataset...

Additionally, it is not clear whether we should add the title or title plus description in **load_queries**.

**Comment by tlinjordet** [comment]
Hello, 

For updated information about A5, please look at
[https://github.com/kbalog/ir-course/blob/master/assignments/A5_errata.md](https://github.com/kbalog/ir-course/blob/master/assignments/A5_errata.md). 

Setting `term_statistics=False` in `get_doc_term_freqs()` is not recommended as the code cell in question is read-only and the runtime of the A5 notebook is not noticeably affected by such a change. 

As for the `load_queries` description, please review the description in the A5 notebook again. Could you please explain how the description is ambiguous?

**Comment by BerntA** [comment]
Hi, thanks, I was somewhat conflicted about the re-ranking, because the old test expected 100 hits when I only managed to get 16, however I did get 100+ hits when loading the title + description for the queries (which naturally broke a bunch of other stuff though). But this has been cleared up now, since the test in fact should expect 16 hits and not 100!
